#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : frozen
Version  : 1.1.1
Release  : 1
URL      : https://github.com/serge-sans-paille/frozen/archive/1.1.1/frozen-1.1.1.tar.gz
Source0  : https://github.com/serge-sans-paille/frozen/archive/1.1.1/frozen-1.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: frozen-data = %{version}-%{release}
Requires: frozen-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-use-consistent-integer-types.patch

%description
Frozen
######
.. image:: https://travis-ci.org/serge-sans-paille/frozen.svg?branch=master
:target: https://travis-ci.org/serge-sans-paille/frozen

%package data
Summary: data components for the frozen package.
Group: Data

%description data
data components for the frozen package.


%package dev
Summary: dev components for the frozen package.
Group: Development
Requires: frozen-data = %{version}-%{release}
Provides: frozen-devel = %{version}-%{release}
Requires: frozen = %{version}-%{release}

%description dev
dev components for the frozen package.


%package license
Summary: license components for the frozen package.
Group: Default

%description license
license components for the frozen package.


%prep
%setup -q -n frozen-1.1.1
cd %{_builddir}/frozen-1.1.1
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692645343
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1692645343
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/frozen
cp %{_builddir}/frozen-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/frozen/a4c1b7bde224e6c35f3a69542c31b60f13d61b26 || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/frozen/algorithm.h
/usr/include/frozen/bits/algorithms.h
/usr/include/frozen/bits/basic_types.h
/usr/include/frozen/bits/constexpr_assert.h
/usr/include/frozen/bits/defines.h
/usr/include/frozen/bits/elsa.h
/usr/include/frozen/bits/elsa_std.h
/usr/include/frozen/bits/exceptions.h
/usr/include/frozen/bits/hash_string.h
/usr/include/frozen/bits/pmh.h
/usr/include/frozen/bits/version.h
/usr/include/frozen/map.h
/usr/include/frozen/random.h
/usr/include/frozen/set.h
/usr/include/frozen/string.h
/usr/include/frozen/unordered_map.h
/usr/include/frozen/unordered_set.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/frozen/a4c1b7bde224e6c35f3a69542c31b60f13d61b26
